### ISSUE TITLE
Missing google-services.json

### ISSUE THREAD

**Issue by benefice-alfa** [udacity/ShoppingListPlusPlus#18]
On Lesson 1 i try to compile this code but it failed because google-services.json file is missing.
i've try to find it inside the project but i can not see it everywhere. Where is it?

Thanks for help.

**Comment by benefice-alfa** [comment]
my bad. google-serverces.json file is not necessary for Lesson 1. the issue is ,i just clone the wrong repo.

**Comment by stevealbertwong** [comment]
I am having the same issue running the final master/final version of the app. So did you find or not find the google-services.json ? Thanks Thanks :D

**Comment by stevealbertwong** [comment]
http://stackoverflow.com/questions/33866061/file-google-services-json-is-missing-from-module-root-folder-the-google-service
This post helps.
