### ISSUE TITLE
'UniqueFireBaseRootUrl'

### ISSUE THREAD

**Issue by YMosheL** [udacity/ShoppingListPlusPlus#2]
Could not find property 'UniqueFireBaseRootUrl' ...
Where do I put my unique firebase url in order to be able to compile it ?
Thank you

**Comment by Kondenko** [comment]
The issue is closed, but in case someone else has this problem:

Open **ShoppingLIstPlusPlus / app / build.gradle** and find this block.
```gradle
 buildTypes.each {
        it.buildConfigField 'String', 'UNIQUE_FIREBASE_ROOT_URL', 'https://example.firebaseio.com/'
    }
```
Replace https://example.firebaseio.com with the url of your app.
