### ISSUE TITLE
getTimestampLastChangedReverseLong Method Name is incorrect

### ISSUE THREAD

**Issue by udacityandroid** [udacity/ShoppingListPlusPlus#6]
Commit https://github.com/udacity/ShoppingListPlusPlus/commit/dbf78669f51ed7dddc191c6e9b3796327d2736df the method should be named getTimestampLastChangedReverseLong not getTimestampLastChangedReverse

**Comment by ceruleanotter** [comment]
This has been fixed and the fix will be pushed during the lesson 4/5 update.
